name: produitsapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  firebase_ui_auth: ^1.0.0
  provider: ^6.1.2
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/souris1.jpeg
    - assets/souris2.jpeg
    - assets/souris3.jpeg 
